
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jet
 */
public class login extends javax.swing.JFrame {
  Connection con;
    PreparedStatement statement;
    Statement st;
    String cs;
    boolean next;
    String password;
    
    String query;
    ResultSet rs;
    String user;
    /**
     * Creates new form login
     */
    public login() {
        con=null;
        st=null;
        statement=null;
        next=false;
        cs="jdbc:mysql://localhost:3306/saloondb";
     
        password="peacebewithyouall2020";
        user = "root";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwd = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uname1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnlog = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(java.awt.Color.blue);
        jButton2.setFont(new java.awt.Font("Ubuntu Condensed", 1, 24)); // NOI18N
        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 60, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Login below to proceed");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 380, 50));

        jLabel5.setFont(new java.awt.Font("Noto Sans Mono CJK TC Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Welcome to");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, 50));

        jLabel4.setFont(new java.awt.Font("Noto Sans Mono CJK TC Bold", 1, 27)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("iSaloon");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, 50));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Have no account yet, contact admin for one");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 360, 60));

        passwd.setBackground(new java.awt.Color(150, 122, 94));
        passwd.setFont(new java.awt.Font("Ubuntu Light", 0, 20)); // NOI18N
        passwd.setForeground(java.awt.Color.white);
        passwd.setCaretColor(java.awt.Color.green);
        kGradientPanel2.add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 420, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Password");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 200, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welcomeimage.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        uname1.setBackground(new java.awt.Color(150, 122, 94));
        uname1.setFont(new java.awt.Font("Ubuntu Light", 0, 20)); // NOI18N
        uname1.setForeground(java.awt.Color.white);
        uname1.setCaretColor(java.awt.Color.green);
        kGradientPanel2.add(uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 420, 50));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Username/phone");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 250, 40));

        btnlog.setBackground(new java.awt.Color(255, 255, 0));
        btnlog.setFont(new java.awt.Font("STIX", 0, 24)); // NOI18N
        btnlog.setForeground(new java.awt.Color(255, 255, 255));
        btnlog.setText("Login");
        btnlog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        btnlog.setContentAreaFilled(false);
        btnlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogMouseClicked(evt);
            }
        });
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 190, 40));

        jCheckBox1.setFont(new java.awt.Font("Ubuntu Condensed", 0, 17)); // NOI18N
        jCheckBox1.setForeground(java.awt.Color.white);
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 160, 30));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
         String u = uname1.getText();
        String pass = passwd.getText().toString();

        try {
            // TODO add your handling code here:
           Class.forName("com.mysql.cj.jdbc.Driver"); //registers drivers we configured
            con=DriverManager.getConnection(cs,user,password);
            st=con.createStatement();
            query="SELECT * FROM user where uname ='"+u+"' OR phone ='"+u+"' AND password = '"+pass+"' LIMIT 1";

            ResultSet rs=  st.executeQuery(query);
            if(rs.first()){

                String ro = rs.getString("rolename");
                String un = rs.getString("uname");
                String homename1 = rs.getString("fname");
               String homename2 = rs.getString("lname");
               String finalname = ""+homename1+" "+homename2+"";
                if(ro.equals("Admin")){
                    JOptionPane.showMessageDialog(null,"Welcome back "+un+", click 'OK' to proceed  to Admin homepage ");

                    adminhome ad = new adminhome();
                    ad.setVisible(true);
                    ad.logsname.setText(finalname);
                    ad.setLocationRelativeTo(null);
                    this.dispose();
                    

                }
                else{

                    JOptionPane.showMessageDialog(null,"Welcome back "+un+",click 'OK' to proceed to Worker's homepage ");

                    workerhome wk = new workerhome();
                    wk.unameworkerhome.setText(un);                      
                    this.dispose();
                    wk.main2();
                }

            }

            else{
                JOptionPane.showMessageDialog(null,"Hey!, I can't trace you anywhere! check your info and try again");
                uname1.setText("");
                passwd.setText("");
            }
        } catch (ClassNotFoundException ex) {
          Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnlogMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
        passwd.setEchoChar((char)0);
        } else{
        passwd.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               login lg =  new login();
               lg.setVisible(true);
               lg.setLocationRelativeTo(null);
               lg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlog;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JTextField uname1;
    // End of variables declaration//GEN-END:variables
}
